import { Picture } from '../picture';
export const PICTURES: Picture[] = [
  {uid: 1, path: 'app/mock-pictures/1.jpg'},
  {uid: 2, path: 'app/mock-pictures/2.jpg'},
  {uid: 3, path: 'app/mock-pictures/3.jpg'},
  {uid: 4, path: 'app/mock-pictures/4.jpg'},
  {uid: 5, path: 'app/mock-pictures/5.jpg'},
  {uid: 6, path: 'app/mock-pictures/1.jpg'},
  {uid: 7, path: 'app/mock-pictures/2.jpg'},
  {uid: 8, path: 'app/mock-pictures/3.jpg'},
  {uid: 9, path: 'app/mock-pictures/4.jpg'},
  {uid: 10, path: 'app/mock-pictures/5.jpg'},
  {uid: 11, path: 'app/mock-pictures/1.jpg'},
  {uid: 12, path: 'app/mock-pictures/2.jpg'},
  {uid: 13, path: 'app/mock-pictures/3.jpg'},
  {uid: 14, path: 'app/mock-pictures/4.jpg'},
  {uid: 15, path: 'app/mock-pictures/5.jpg'},
  {uid: 16, path: 'app/mock-pictures/1.jpg'},
  {uid: 17, path: 'app/mock-pictures/2.jpg'},
  {uid: 18, path: 'app/mock-pictures/3.jpg'},
  {uid: 19, path: 'app/mock-pictures/4.jpg'},
  {uid: 20, path: 'app/mock-pictures/5.jpg'},
  {uid: 21, path: 'app/mock-pictures/1.jpg'},
  {uid: 22, path: 'app/mock-pictures/2.jpg'},
  {uid: 23, path: 'app/mock-pictures/3.jpg'},
  {uid: 24, path: 'app/mock-pictures/4.jpg'},
  {uid: 25, path: 'app/mock-pictures/5.jpg'}
];
